import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translation dictionary
const translations = {
  en: {
    // Navigation
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.stations": "Stations",
    "nav.contact": "Contact",

    // Homepage
    "home.hero.badge": "🚗 The Future of EV Energy",
    "home.hero.title": "Fast and Reliable EV Battery Swap Stations",
    "home.hero.subtitle":
      "Skip the wait, swap the battery. Get back on the road in under 3 minutes with our revolutionary battery swap technology.",
    "home.hero.findStation": "Find Station",
    "home.hero.watchDemo": "Watch Demo",
    "home.hero.avgSwapTime": "3 min",
    "home.hero.avgSwapTimeLabel": "Average swap time",
    "home.hero.availability": "24/7",
    "home.hero.availabilityLabel": "Always available",
    "home.hero.batteriesAvailable": "batteries available",

    // Stats
    "stats.swapsCompleted": "Battery Swaps Completed",
    "stats.stationsNationwide": "Stations Nationwide",
    "stats.happyCustomers": "Happy Customers",
    "stats.uptimeReliability": "Uptime Reliability",

    // Features
    "features.title": "Why Choose EVSwap?",
    "features.subtitle":
      "Experience the future of EV energy with our innovative battery swap technology",
    "features.ultraFast.title": "Ultra-Fast Swaps",
    "features.ultraFast.desc":
      "Complete battery swap in under 3 minutes - faster than filling up gas",
    "features.alwaysCharged.title": "Always Charged",
    "features.alwaysCharged.desc":
      "Get a fully charged battery every time with our smart inventory system",
    "features.nationwide.title": "Nationwide Network",
    "features.nationwide.desc":
      "24 stations and growing across major cities and highways",
    "features.safeReliable.title": "Safe & Reliable",
    "features.safeReliable.desc":
      "All batteries tested and certified for optimal performance and safety",

    // Stations
    "stations.title": "Find Stations Near You",
    "stations.subtitle": "Our growing network covers major cities and highways",
    "stations.mapTitle": "Interactive Station Map",
    "stations.mapDesc": "Find the nearest station with real-time availability",
    "stations.viewFullMap": "View Full Map",
    "stations.downtownHub": "Downtown Hub",
    "stations.mallStation": "Mall Station",
    "stations.airportTerminal": "Airport Terminal",
    "stations.maintenanceMode": "Maintenance mode",

    // Pricing
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle":
      "Choose the plan that works best for your driving needs",
    "pricing.payPerSwap": "Pay Per Swap",
    "pricing.monthlyUnlimited": "Monthly Unlimited",
    "pricing.enterprise": "Enterprise",
    "pricing.mostPopular": "Most Popular",
    "pricing.perSwap": "per swap",
    "pricing.perMonth": "per month",
    "pricing.customPricing": "pricing",
    "pricing.payPerSwap.desc": "Perfect for occasional users",
    "pricing.monthlyUnlimited.desc": "Best for regular commuters",
    "pricing.enterprise.desc": "For fleets and businesses",
    "pricing.payPerSwap.feature1": "No monthly commitment",
    "pricing.payPerSwap.feature2": "Pay only when you swap",
    "pricing.payPerSwap.feature3": "Access to all stations",
    "pricing.payPerSwap.feature4": "Mobile app included",
    "pricing.monthlyUnlimited.feature1": "Unlimited battery swaps",
    "pricing.monthlyUnlimited.feature2": "Priority reservation",
    "pricing.monthlyUnlimited.feature3": "24/7 customer support",
    "pricing.monthlyUnlimited.feature4": "10% discount on accessories",
    "pricing.enterprise.feature1": "Volume discounts",
    "pricing.enterprise.feature2": "Dedicated account manager",
    "pricing.enterprise.feature3": "Custom billing solutions",
    "pricing.enterprise.feature4": "Priority station access",
    "pricing.getStarted": "Get Started",

    // Testimonials
    "testimonials.title": "What Our Customers Say",
    "testimonials.subtitle": "Join thousands of satisfied EV drivers",
    "testimonials.customer1.name": "Sarah Chen",
    "testimonials.customer1.role": "Daily Commuter",
    "testimonials.customer1.comment":
      "EVSwap has revolutionized my daily commute. No more waiting hours for charging!",
    "testimonials.customer2.name": "Mike Rodriguez",
    "testimonials.customer2.role": "Uber Driver",
    "testimonials.customer2.comment":
      "As a rideshare driver, time is money. EVSwap keeps me on the road earning.",
    "testimonials.customer3.name": "Jennifer Park",
    "testimonials.customer3.role": "Fleet Manager",
    "testimonials.customer3.comment":
      "Our delivery fleet runs 24/7 thanks to EVSwap's reliable network.",

    // CTA Section
    "cta.title": "Ready to Experience the Future?",
    "cta.subtitle":
      "Join thousands of drivers who have already made the switch to instant battery swaps",
    "cta.signUpNow": "Sign Up Now",
    "cta.contactSales": "Contact Sales",

    // Footer
    "footer.description":
      "Revolutionizing EV energy with fast, reliable battery swap stations.",
    "footer.services": "Services",
    "footer.batterySwap": "Battery Swap",
    "footer.findStations": "Find Stations",
    "footer.subscriptionPlans": "Subscription Plans",
    "footer.enterpriseSolutions": "Enterprise Solutions",
    "footer.support": "Support",
    "footer.helpCenter": "Help Center",
    "footer.faqs": "FAQs",
    "footer.contactSupport": "Contact Support",
    "footer.roadsideAssistance": "Roadside Assistance",
    "footer.contact": "Contact",
    "footer.copyright": "© 2024 EVSwap. All rights reserved.",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",

    // Login
    "login.title": "SIGN IN",
    "login.subtitle": "Sign in to access your EVSwap account",
    "login.email": "Email",
    "login.password": "Password",
    "login.signIn": "Sign In",
    "login.demoAccess": "Demo Access",
    "login.backToHome": "← Back to Homepage",
    "login.continueWithGoogle": "Continue with Google",
    "login.continueWithFacebook": "Continue with Facebook",
    "login.continueWithGithub": "Continue with GitHub",
    "login.orContinueWithEmail": "Or continue with email",
    "login.enterEmail": "Enter your email",
    "login.enterPassword": "Enter your password",
    "login.rememberMe": "Remember me",
    "login.forgotPassword": "Forgot password?",
    "login.tryPlatform": "Try the platform with different user roles:",
    "login.evDriverPortal": "EV Driver Portal",
    "login.stationStaffPortal": "Station Staff Portal",
    "login.adminDashboard": "Admin Dashboard",
    "login.dontHaveAccount": "Don't have an account?",
    "login.signUpHere": "Sign up here",
    "login.batterySwapManagement": "Battery Swap Station Management",

    // Register
    "register.name": "Name",
    "register.joinEVSwap": "Join EVSwap",
    "register.createAccount": "Create your account to get started",
    "register.personalInfo": "Personal Information",
    "register.personalInfoDesc": "Tell us about yourself",
    "register.accountSetup": "Account Setup",
    "register.accountSetupDesc": "Set up your login credentials",
    "register.roleSelection": "Role Selection",
    "register.roleSelectionDesc": "Choose your account type",
    "register.firstName": "First Name",
    "register.lastName": "Last Name",
    "register.firstNamePlaceholder": "Enter your first name",
    "register.lastNamePlaceholder": "Enter your last name",
    "register.phoneNumber": "Phone Number",
    "register.emailAddress": "Email Address",
    "register.password": "Password",
    "register.confirmPassword": "Confirm Password",
    "register.passwordPlaceholder": "Create a strong password",
    "register.confirmPasswordPlaceholder": "Confirm your password",
    "register.passwordHint": "Must be at least 8 characters long",
    "register.chooseRole": "Choose Your Role",
    "register.driver": "EV Driver",
    "register.driverDesc":
      "Access station locator, book swaps, and manage your vehicles",
    "register.staff": "Station Staff",
    "register.staffDesc":
      "Manage station operations, inventory, and customer service",
    "register.roleNote": "You can change your role later by contacting support",
    "register.next": "Next",
    "register.back": "Back",
    "register.backToLogin": "Back to Login",
    "register.createAccountButton": "Create Account", // Changed from duplicate 'register.createAccount'
    "register.creating": "Creating Account...",
    "register.alreadyHaveAccount": "Already have an account?",
    "register.signIn": "Sign in",
    "register.termsText": "By creating an account, you agree to our",
    "register.termsOfService": "Terms of Service",
    "register.and": "and",
    "register.privacyPolicy": "Privacy Policy",
    "register.firstNameRequired": "First name is required",
    "register.lastNameRequired": "Last name is required",
    "register.phoneRequired": "Phone number is required",
    "register.emailRequired": "Email is required",
    "register.emailInvalid": "Please enter a valid email address",
    "register.passwordRequired": "Password is required",
    "register.passwordTooShort": "Password must be at least 6 characters",
    "register.confirmPasswordRequired": "Please confirm your password",
    "register.passwordMismatch": "Passwords do not match",
    "register.roleRequired": "Please select your role",
    "register.defaultDriverRole": "Starting as EV Driver",
    "register.defaultDriverRoleDesc":
      "You're signing up as an EV Driver. You can request to become a Station Staff later through your profile settings.",
    "register.namePlaceholder": "Enter your name",

    // Driver Portal
    "driver.findStations": "Find Stations",
    "driver.swap": "Swap",
    "driver.history": "History",
    "driver.profile": "Profile",
    "driver.support": "Support",
    "driver.nearbyStations": "Nearby Stations",
    "driver.nearbyStationsDesc": "Find and reserve battery swap stations",
    "driver.interactiveMap": "Interactive map with real-time availability",
    "driver.showingStations": "Showing",
    "driver.stationsNearby": "stations nearby",
    "driver.useMyLocation": "Use My Location",
    "driver.availableStations": "Available Stations",
    "driver.filter": "Filter",
    "driver.searchStations": "Search stations...",
    "driver.available": "available",
    "driver.open": "open",
    "driver.maintenance": "maintenance",
    "driver.reserve": "Reserve",
    "driver.activeReservation": "Active Reservation",
    "driver.activeReservationDesc": "Your current battery swap booking",
    "driver.confirmed": "Confirmed",
    "driver.today": "Today",
    "driver.checkIn": "Check-in",
    "driver.directions": "Directions",
    "driver.subscriptionStatus": "Subscription Status",
    "driver.subscriptionStatusDesc": "Your current plan and usage",
    "driver.active": "Active",
    "driver.swapsUsed": "Swaps Used",
    "driver.unlimited": "Unlimited",
    "driver.nextBilling": "Next billing:",
    "driver.managePlan": "Manage Plan",
    "driver.swapHistory": "Swap History",
    "driver.swapHistoryDesc": "Your recent battery swaps and transactions",
    "driver.loadMoreHistory": "Load More History",
    "driver.completed": "completed",
    "driver.profileInformation": "Profile Information",
    "driver.fullName": "Full Name",
    "driver.email": "Email",
    "driver.phone": "Phone",
    "driver.saveChanges": "Save Changes",
    "driver.myVehicles": "My Vehicles",
    "driver.myVehiclesDesc": "Manage your registered vehicles",
    "driver.addVehicle": "Add Vehicle",
    "driver.contactSupport": "Contact Support",
    "driver.contactSupportDesc": "Get help with your EVSwap experience",
    "driver.callSupport": "Call Support",
    "driver.liveChat": "Live Chat",
    "driver.reportIssue": "Report Issue",
    "driver.safetyAndSecurity": "Safety & Security",
    "driver.safetySecurityDesc": "Account security settings",
    "driver.changePassword": "Change Password",
    "driver.twoFactorAuth": "Two-Factor Authentication",
    "driver.bookBatterySwap": "Book Battery Swap",
    "driver.completeReservation": "Complete your reservation in",
    "driver.moreSteps": "more steps",
    "driver.selectVehicle": "Select Vehicle",
    "driver.addNewVehicle": "Add New Vehicle",
    "driver.cancel": "Cancel",
    "driver.next": "Next",
    "driver.back": "Back",
    "driver.chooseTimeSlot": "Choose Time Slot",
    "driver.confirmBooking": "Confirm Booking",
    "driver.station": "Station:",
    "driver.vehicle": "Vehicle:",
    "driver.dateTime": "Date & Time:",
    "driver.total": "Total:",
    "driver.bookingConfirmed": "Booking Confirmed!",
    "driver.swapReserved": "Your swap is reserved for today at",
    "driver.bookingCode": "Booking Code",
    "driver.showQRCode": "Show this QR code at the station",
    "driver.viewQRCode": "View QR Code",
    "driver.close": "Close",
    "driver.checkInQRCode": "Check-in QR Code",
    "driver.scanAtStation":
      "Scan this code at the station to start your battery swap",
    "driver.expiresIn": "Expires in 2 hours",
    "driver.saveToPhone": "Save to Phone",
    "driver.battery": "Battery:",

    // Staff Portal
    "staff.inventory": "Inventory",
    "staff.transactions": "Transactions",
    "staff.reports": "Reports",
    "staff.incidents": "Incidents",
    "staff.queueManagement": "Queue Management",
    "staff.todaysBookings": "Today's Bookings",
    "staff.todaysBookingsDesc": "Manage customer reservations and walk-ins",
    "staff.pending": "pending",
    "staff.inProgress": "in-progress",
    "staff.confirmed": "confirmed",
    "staff.startSwap": "Start Swap",
    "staff.batteryInventory": "Battery Inventory",
    "staff.filter": "Filter",
    "staff.newInspection": "New Inspection",
    "staff.slot": "Slot",
    "staff.health": "Health",
    "staff.voltage": "Voltage",
    "staff.cycles": "Cycles",
    "staff.temperature": "Temperature",
    "staff.lastSwap": "Last Swap",
    "staff.full": "full",
    "staff.charging": "charging",
    "staff.maintenance": "maintenance",
    "staff.empty": "empty",
    "staff.recentTransactions": "Recent Transactions",
    "staff.recentTransactionsDesc": "Today's completed battery swaps",
    "staff.subscription": "subscription",
    "staff.card": "card",
    "staff.cash": "cash",
    "staff.out": "Out",
    "staff.in": "In",
    "staff.shiftSummary": "Shift Summary",
    "staff.shiftSummaryDesc": "Your performance today",
    "staff.swapsCompleted": "Swaps Completed",
    "staff.revenueGenerated": "Revenue Generated",
    "staff.avgSwapTime": "Average Swap Time",
    "staff.customerRating": "Customer Rating",
    "staff.exportReport": "Export Report",
    "staff.stationAlerts": "Station Alerts",
    "staff.stationAlertsDesc": "Issues requiring attention",
    "staff.lowBatteryAlert": "Low Battery Alert",
    "staff.lowBatteryAlertDesc": "3 batteries below 20% health",
    "staff.maintenanceRequired": "Maintenance Required",
    "staff.maintenanceRequiredDesc": "Slot B1 needs inspection",
    "staff.batterySwapProcess": "Battery Swap Process",
    "staff.batterySwapProcessDesc":
      "Complete the battery swap for customer SW-2024-001",
    "staff.customerInformation": "Customer Information",
    "staff.name": "Name",
    "staff.vehicle": "Vehicle",
    "staff.bookingCode": "Booking Code",
    "staff.batteryModel": "Battery Model",
    "staff.batteryOut": "Battery OUT",
    "staff.batteryIn": "Battery IN",
    "staff.currentBattery": "Current Battery",
    "staff.chargeLevel": "Charge Level",
    "staff.destinationSlot": "Destination Slot",
    "staff.newBattery": "New Battery",
    "staff.qrCodeScanned": "QR Code Scanned",
    "staff.pinVerified": "PIN Verified",
    "staff.batterySwapComplete": "Battery Swap Complete",
    "staff.markComplete": "Mark Complete",
    "staff.processPayment": "Process Payment",
    "staff.completeAndPrint": "Complete & Print Receipt",
    "staff.batteryReturnInspection": "Battery Return Inspection",
    "staff.batteryReturnInspectionDesc":
      "Inspect the returned battery for any damage or issues",
    "staff.batteryId": "Battery ID",
    "staff.customer": "Customer",
    "staff.inspectionChecklist": "Inspection Checklist",
    "staff.physicalDamage": "Physical damage check",
    "staff.connectorInspection": "Connector inspection",
    "staff.temperatureReading": "Temperature reading",
    "staff.voltageTest": "Voltage test",
    "staff.capacityVerification": "Capacity verification",
    "staff.inspectionNotes": "Inspection Notes",
    "staff.inspectionNotesPlaceholder": "Any issues or observations...",
    "staff.photoDocumentation": "Photo Documentation",
    "staff.takePhoto": "Take Photo",
    "staff.uploadFile": "Upload File",
    "staff.completeInspection": "Complete Inspection",
    "staff.pointOfSale": "Point of Sale",
    "staff.pointOfSaleDesc": "Process payment for battery swap",
    "staff.batterySwapService": "Battery Swap Service",
    "staff.cardPayment": "Card Payment",
    "staff.qrPayment": "QR Payment",
    "staff.cashPayment": "Cash Payment",
    "staff.printReceipt": "Print Receipt",
    "staff.todaysSwaps": "Today's Swaps",
    "staff.revenue": "Revenue",
    "staff.avgTime": "Avg Time",
    "staff.rating": "Rating",
    "staff.lowBattery": "Low Battery",

    // Admin Dashboard
    "admin.overview": "Overview",
    "admin.stations": "Stations",
    "admin.analytics": "Analytics",
    "admin.aiInsights": "AI Insights",
    "admin.users": "Users",
    "admin.alerts": "Alerts",
    "admin.settings": "Settings",
    "admin.totalRevenue": "Total Revenue",
    "admin.totalSwaps": "Total Swaps",
    "admin.activeStations": "Active Stations",
    "admin.customers": "Customers",
    "admin.allOnline": "All Online",
    "admin.newCustomers": "new",
    "admin.revenueTrends": "Revenue Trends",
    "admin.revenueTrendsDesc": "Monthly revenue and swap volume",
    "admin.batteryHealthDistribution": "Battery Health Distribution",
    "admin.batteryHealthDistributionDesc": "Current battery fleet condition",
    "admin.avgSwapTime": "Avg Swap Time",
    "admin.systemUptime": "System Uptime",
    "admin.customerRating": "Customer Rating",
    "admin.batteryEfficiency": "Battery Efficiency",
    "admin.stationManagement": "Station Management",
    "admin.filter": "Filter",
    "admin.addStation": "Add Station",
    "admin.swaps": "Swaps",
    "admin.revenue": "Revenue",
    "admin.utilization": "Utilization",
    "admin.batteryFleetManagement": "Battery Fleet Management",
    "admin.export": "Export",
    "admin.fleetOverview": "Fleet Overview",
    "admin.totalBatteries": "Total Batteries",
    "admin.healthy": "Healthy (>90%)",
    "admin.degraded": "Degraded (70-90%)",
    "admin.critical": "Critical (<70%)",
    "admin.maintenanceSchedule": "Maintenance Schedule",
    "admin.urgent": "Urgent",
    "admin.urgentDesc": "batteries",
    "admin.immediateAttention": "Immediate attention required",
    "admin.thisWeek": "This Week",
    "admin.thisWeekDesc": "batteries",
    "admin.scheduledMaintenance": "Scheduled maintenance",
    "admin.nextMonth": "Next Month",
    "admin.nextMonthDesc": "batteries",
    "admin.routineInspection": "Routine inspection",
    "admin.batteryAllocation": "Battery Allocation",
    "admin.optimizeAllocation": "Optimize Allocation",
    "admin.customerManagement": "Customer Management",
    "admin.searchCustomers": "Search customers...",
    "admin.addCustomer": "Add Customer",
    "admin.customer": "Customer",
    "admin.plan": "Plan",
    "admin.status": "Status",
    "admin.actions": "Actions",
    "admin.staffManagement": "Staff Management",
    "admin.addStaff": "Add Staff",
    "admin.name": "Name",
    "admin.role": "Role",
    "admin.station": "Station",
    "admin.performance": "Performance",
    "admin.active": "active",
    "admin.onLeave": "on-leave",
    "admin.suspended": "suspended",
    "admin.aiDemandForecasting": "AI Demand Forecasting",
    "admin.aiDemandForecastingDesc": "Predicted vs actual demand patterns",
    "admin.predicted": "Predicted",
    "admin.actual": "Actual",
    "admin.confidenceScore": "Confidence", // Changed from duplicate 'admin.confidence'
    "admin.batteryOptimization": "Battery Optimization",
    "admin.batteryOptimizationDesc":
      "AI-powered battery allocation recommendations",
    "admin.recommendation": "Recommendation",
    "admin.redistributeBatteries":
      "Redistribute 5 batteries from Airport Terminal to Downtown Hub",
    "admin.schedulePreemptive":
      "Schedule preemptive maintenance for 12 batteries in degraded state",
    "admin.impact": "Impact",
    "admin.increaseUtilization": "+15% utilization improvement",
    "admin.reduceMaintenance": "30% reduction in emergency maintenance",
    "admin.confidence": "Confidence", // This is the main confidence key
    "admin.systemAlerts": "System Alerts",
    "admin.criticalLevel": "critical", // Changed from duplicate 'admin.critical'
    "admin.warning": "warning",
    "admin.info": "info",
    "admin.stationBatteryHealth": "Station B1 battery health below 50%",
    "admin.highDemandPredicted": "High demand predicted for 6-8 PM",
    "admin.monthlyTarget": "Monthly revenue target achieved",
    "admin.paymentGateway": "Payment gateway timeout errors",
    "admin.allStations": "All Stations",
    "admin.system": "System",
    "admin.markResolved": "Mark Resolved",
    "admin.viewDetails": "View Details",
    "admin.batteries": "Batteries",
    "admin.staff": "Staff",

    // Admin Battery Management
    "admin.sevenDays": "7 days",
    "admin.thirtyDays": "30 days",
    "admin.ninetyDays": "90 days",
    "admin.urgentBatteries": "Urgent: 8 batteries",
    "admin.thisWeekBatteries": "This Week: 15 batteries",
    "admin.nextMonthBatteries": "Next Month: 23 batteries",
    "admin.downtownHub": "Downtown Hub",
    "admin.mallStation": "Mall Station",
    "admin.airportTerminal": "Airport Terminal",
    "admin.highwayRestStop": "Highway Rest Stop",
    "admin.universityCampus": "University Campus",

    // Admin Customer & Staff Plans/Roles
    "admin.monthlyUnlimited": "Monthly Unlimited",
    "admin.payPerSwap": "Pay Per Swap",
    "admin.enterprise": "Enterprise",
    "admin.stationManager": "Station Manager",
    "admin.technician": "Technician",
    "admin.supervisor": "Supervisor",

    // Admin Alerts Messages
    "admin.alertTime2Min": "2 min ago",
    "admin.alertTime15Min": "15 min ago",
    "admin.alertTime1Hour": "1 hour ago",
    "admin.alertTime2Hours": "2 hours ago",

    // Common
    "common.logout": "Logout",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.view": "View",
    "common.close": "Close",
    "common.settings": "Settings",
  },
  vi: {
    // Navigation
    "nav.signIn": "Đăng Nhập",
    "nav.getStarted": "Bắt Đầu",
    "nav.features": "Tính Năng",
    "nav.pricing": "Bảng Giá",
    "nav.stations": "Trạm",
    "nav.contact": "Liên Hệ",

    // Homepage
    "home.hero.badge": "🚗 Tương Lai Năng Lượng EV",
    "home.hero.title": "Trạm Thay Pin EV Nhanh Chóng và Đáng Tin Cậy",
    "home.hero.subtitle":
      "Bỏ qua thời gian chờ, thay pin ngay. Quay lại đường trong vòng chưa đầy 3 phút với công nghệ thay pin cách mạng của chúng tôi.",
    "home.hero.findStation": "Tìm Trạm",
    "home.hero.watchDemo": "Xem Demo",
    "home.hero.avgSwapTime": "3 phút",
    "home.hero.avgSwapTimeLabel": "Thời gian thay trung bình",
    "home.hero.availability": "24/7",
    "home.hero.availabilityLabel": "Luôn sẵn sàng",
    "home.hero.batteriesAvailable": "pin có sẵn",

    // Stats
    "stats.swapsCompleted": "Lần Thay Pin Hoàn Thành",
    "stats.stationsNationwide": "Trạm Toàn Quốc",
    "stats.happyCustomers": "Khách Hàng Hài Lòng",
    "stats.uptimeReliability": "Độ Tin Cậy Hoạt Động",

    // Features
    "features.title": "Tại Sao Chọn EVSwap?",
    "features.subtitle":
      "Trải nghiệm tương lai năng lượng EV với công nghệ thay pin sáng tạo của chúng tôi",
    "features.ultraFast.title": "Thay Pin Siêu Nhanh",
    "features.ultraFast.desc":
      "Hoàn thành thay pin trong vòng dưới 3 phút - nhanh hơn đổ xăng",
    "features.alwaysCharged.title": "Luôn Đầy Pin",
    "features.alwaysCharged.desc":
      "Luôn nhận được pin đầy với hệ thống quản lý thông minh của chúng tôi",
    "features.nationwide.title": "Mạng Lưới Toàn Quốc",
    "features.nationwide.desc":
      "24 trạm và đang mở rộng trên các thành phố lớn và đường cao tốc",
    "features.safeReliable.title": "An Toàn & Đáng Tin Cậy",
    "features.safeReliable.desc":
      "Tất cả pin được kiểm tra và chứng nhận cho hiệu suất và an toàn tối ưu",

    // Stations
    "stations.title": "Tìm Trạm Gần Bạn",
    "stations.subtitle":
      "Mạng lưới đang phát triển của chúng tôi bao phủ các thành phố lớn và đường cao tốc",
    "stations.mapTitle": "Bản Đồ Trạm Tương Tác",
    "stations.mapDesc":
      "Tìm trạm gần nhất với tình trạng có sẵn theo thời gian thực",
    "stations.viewFullMap": "Xem Bản Đồ Đầy Đủ",
    "stations.downtownHub": "Trung Tâm Thành Phố",
    "stations.mallStation": "Trạm Trung Tâm Thương Mại",
    "stations.airportTerminal": "Nhà Ga Sân Bay",
    "stations.maintenanceMode": "Chế độ bảo trì",

    // Pricing
    "pricing.title": "Giá Cả Đơn Giản, Minh Bạch",
    "pricing.subtitle": "Chọn gói phù hợp nhất với nhu cầu lái xe của bạn",
    "pricing.payPerSwap": "Trả Theo Lần Thay",
    "pricing.monthlyUnlimited": "Không Giới Hạn Hàng Tháng",
    "pricing.enterprise": "Doanh Nghiệp",
    "pricing.mostPopular": "Phổ Biến Nhất",
    "pricing.perSwap": "mỗi lần thay",
    "pricing.perMonth": "mỗi tháng",
    "pricing.customPricing": "giá tùy chỉnh",
    "pricing.payPerSwap.desc": "Hoàn hảo cho người dùng thỉnh thoảng",
    "pricing.monthlyUnlimited.desc": "Tốt nhất cho người đi làm thường xuyên",
    "pricing.enterprise.desc": "Cho đội xe và doanh nghiệp",
    "pricing.payPerSwap.feature1": "Không cam kết hàng tháng",
    "pricing.payPerSwap.feature2": "Chỉ trả khi thay pin",
    "pricing.payPerSwap.feature3": "Truy cập tất cả các trạm",
    "pricing.payPerSwap.feature4": "Bao gồm ứng dụng di động",
    "pricing.monthlyUnlimited.feature1": "Thay pin không giới hạn",
    "pricing.monthlyUnlimited.feature2": "Đặt chỗ ưu tiên",
    "pricing.monthlyUnlimited.feature3": "Hỗ trợ khách hàng 24/7",
    "pricing.monthlyUnlimited.feature4": "Giảm giá 10% phụ kiện",
    "pricing.enterprise.feature1": "Giảm giá theo số lượng",
    "pricing.enterprise.feature2": "Quản lý tài khoản chuyên dụng",
    "pricing.enterprise.feature3": "Giải pháp thanh toán tùy chỉnh",
    "pricing.enterprise.feature4": "Truy cập trạm ưu tiên",
    "pricing.getStarted": "Bắt Đầu",

    // Testimonials
    "testimonials.title": "Khách Hàng Nói Gì Về Chúng Tôi",
    "testimonials.subtitle": "Tham gia cùng hàng nghìn tài xế EV hài lòng",
    "testimonials.customer1.name": "Sarah Chen",
    "testimonials.customer1.role": "Người Đi Làm Hàng Ngày",
    "testimonials.customer1.comment":
      "EVSwap đã cách mạng hóa chuyến đi làm hàng ngày của tôi. Không còn chờ đợi hàng giờ để sạc!",
    "testimonials.customer2.name": "Mike Rodriguez",
    "testimonials.customer2.role": "Tài Xế Uber",
    "testimonials.customer2.comment":
      "Là tài xế chia sẻ chuyến đi, thời gian là tiền bạc. EVSwap giúp tôi luôn chạy xe và kiếm tiền.",
    "testimonials.customer3.name": "Jennifer Park",
    "testimonials.customer3.role": "Quản Lý Đội Xe",
    "testimonials.customer3.comment":
      "Đội xe giao hàng của chúng tôi hoạt động 24/7 nhờ mng lưới đáng tin cậy của EVSwap.",

    // CTA Section
    "cta.title": "Sẵn Sàng Trải Nghiệm Tương Lai?",
    "cta.subtitle":
      "Tham gia cùng hàng nghìn tài xế đã chuyển sang thay pin tức thì",
    "cta.signUpNow": "Đăng Ký Ngay",
    "cta.contactSales": "Liên Hệ Bán Hàng",

    // Footer
    "footer.description":
      "Cách mạng hóa năng lượng EV với các trạm thay pin nhanh chóng, đáng tin cậy.",
    "footer.services": "Dịch Vụ",
    "footer.batterySwap": "Thay Pin",
    "footer.findStations": "Tìm Trạm",
    "footer.subscriptionPlans": "Gói Đăng Ký",
    "footer.enterpriseSolutions": "Giải Pháp Doanh Nghiệp",
    "footer.support": "Hỗ Trợ",
    "footer.helpCenter": "Trung Tâm Trợ Giúp",
    "footer.faqs": "Câu Hỏi Thường Gặp",
    "footer.contactSupport": "Liên Hệ Hỗ Trợ",
    "footer.roadsideAssistance": "Cứu Hộ Đường Bộ",
    "footer.contact": "Liên Hệ",
    "footer.copyright": "© 2024 EVSwap. Tất cả quyền được bảo lưu.",
    "footer.privacyPolicy": "Chính Sách Bảo Mật",
    "footer.termsOfService": "Điều Khoản Dịch Vụ",

    // Login
    "login.title": "ĐĂNG NHẬP",
    "login.subtitle": "Đăng nhập để truy cập tài khoản EVSwap của bạn",
    "login.email": "Email",
    "login.password": "Mật Khẩu",
    "login.signIn": "Đăng Nhập",
    "login.demoAccess": "Truy Cập Demo",
    "login.backToHome": "← Về Trang Chủ",
    "login.continueWithGoogle": "Tiếp tục với Google",
    "login.continueWithFacebook": "Tiếp tục với Facebook",
    "login.continueWithGithub": "Tiếp tục với GitHub",
    "login.orContinueWithEmail": "Hoặc tiếp tục với email",
    "login.enterEmail": "Nhập email của bạn",
    "login.enterPassword": "Nhập mật khẩu của bạn",
    "login.rememberMe": "Ghi nhớ tôi",
    "login.forgotPassword": "Quên mật khẩu?",
    "login.tryPlatform": "Thử nền tảng với các vai trò người dùng khác nhau:",
    "login.evDriverPortal": "Portal Tài Xế EV",
    "login.stationStaffPortal": "Portal Nhân Viên Trạm",
    "login.adminDashboard": "Bảng Điều Khiển Quản Lý",
    "login.dontHaveAccount": "Không có tài khoản?",
    "login.signUpHere": "Đăng ký tại đây",
    "login.batterySwapManagement": "Quản Lý Trạm Thay Pin",

    // Register
    "register.namePlaceholder": "Hãy nhập tên của bạn",
    "register.name": "Tên",
    "register.joinEVSwap": "Tham Gia EVSwap",
    "register.createAccount": "Tạo tài khoản của bạn để bắt đầu",
    "register.personalInfo": "Thông Tin Cá Nhân",
    "register.personalInfoDesc": "Hãy cho chúng tôi biết về bạn",
    "register.accountSetup": "Thiết Lập Tài Khoản",
    "register.accountSetupDesc": "Thiết lập thông tin đăng nhập của bạn",
    "register.roleSelection": "Chọn Vai Trò",
    "register.roleSelectionDesc": "Chọn loại tài khoản của bạn",
    "register.firstName": "Tên",
    "register.lastName": "Họ",
    "register.firstNamePlaceholder": "Nhập tên của bạn",
    "register.lastNamePlaceholder": "Nhập họ của bạn",
    "register.phoneNumber": "Số Điện Thoại",
    "register.emailAddress": "Địa Chỉ Email",
    "register.password": "Mật Khẩu",
    "register.confirmPassword": "Xác Nhận Mật Khẩu",
    "register.passwordPlaceholder": "Tạo mật khẩu mạnh",
    "register.confirmPasswordPlaceholder": "Xác nhận mật khẩu của bạn",
    "register.passwordHint": "Phải có ít nhất 6 ký tự",
    "register.chooseRole": "Chọn Vai Trò Của Bạn",
    "register.driver": "Tài Xế EV",
    "register.driverDesc":
      "Truy cập tìm trạm, đặt chỗ thay pin, và quản lý xe của bạn",
    "register.staff": "Nhân Viên Trạm",
    "register.staffDesc": "Quản lý hoạt động trạm, kho và dịch vụ khách hàng",
    "register.roleNote":
      "Bạn có thể thay đổi vai trò của mình sau này bằng cách liên hệ hỗ trợ",
    "register.next": "Tiếp",
    "register.back": "Quay lại",
    "register.backToLogin": "Quay Về Đăng Nhập",
    "register.createAccountButton": "Tạo Tài Khoản", // Changed from duplicate 'register.createAccount'
    "register.creating": "Đang Tạo Tài Khoản...",
    "register.alreadyHaveAccount": "Đã có tài khoản?",
    "register.signIn": "Đăng nhập",
    "register.termsText": "Bằng cách tạo tài khoản, bạn đồng ý với",
    "register.termsOfService": "Điều Khoản Dịch Vụ",
    "register.and": "và",
    "register.privacyPolicy": "Chính Sách Bảo Mật",
    "register.firstNameRequired": "Tên là bắt buộc",
    "register.lastNameRequired": "Họ là bắt buộc",
    "register.phoneRequired": "Số điện thoại là bắt buộc",
    "register.emailRequired": "Email là bắt buộc",
    "register.emailInvalid": "Vui lòng nhập địa chỉ email hợp lệ",
    "register.passwordRequired": "Mật khẩu là bắt buộc",
    "register.passwordTooShort": "Mật khẩu phải có ít nhất 6 ký tự",
    "register.confirmPasswordRequired": "Vui lòng xác nhận mật khẩu",
    "register.passwordMismatch": "Mật khẩu không khớp",
    "register.roleRequired": "Vui lòng chọn vai trò của bạn",
    "register.defaultDriverRole": "Bắt đầu là Tài Xế EV",
    "register.defaultDriverRoleDesc":
      "Bạn đang đăng ký là Tài Xế EV. Bạn có thể yêu cầu trở thành Nhân Viên Trạm sau thông qua cài đặt hồ sơ của bạn.",

    // Driver Portal
    "driver.findStations": "Tìm Trạm",
    "driver.swap": "Thay Pin",
    "driver.history": "Lịch Sử",
    "driver.profile": "Hồ Sơ",
    "driver.support": "Hỗ Trợ",
    "driver.nearbyStations": "Trạm Gần Bạn",
    "driver.nearbyStationsDesc": "Tìm và đặt chỗ trạm thay pin",
    "driver.interactiveMap": "Bản Đồ Tương Tác với Tình Trạng Có Sẵn",
    "driver.showingStations": "Đang Hiển Thị",
    "driver.stationsNearby": "trạm gần đây",
    "driver.useMyLocation": "Sử dụng Vị Trí Của Tôi",
    "driver.availableStations": "Trạm Có Sẵn",
    "driver.filter": "Lọc",
    "driver.searchStations": "Tìm trạm...",
    "driver.available": "có sẵn",
    "driver.open": "mở",
    "driver.maintenance": "bảo trì",
    "driver.reserve": "Đặt Chỗ",
    "driver.activeReservation": "Đặt Chỗ Hoạt Động",
    "driver.activeReservationDesc": "Đơn đặt chỗ pin hiện tại của bạn",
    "driver.confirmed": "đã xác nhận",
    "driver.today": "Hôm Nay",
    "driver.checkIn": "Check-in",
    "driver.directions": "Đường Đi",
    "driver.subscriptionStatus": "Trạng Thái Đăng Ký",
    "driver.subscriptionStatusDesc": "Gói và sử dụng hiện tại của bạn",
    "driver.active": "Hoạt Động",
    "driver.swapsUsed": "Lần Thay Pin Đã Sử Dụng",
    "driver.unlimited": "Không Giới Hạn",
    "driver.nextBilling": "Hóa Đơn Tiếp Theo:",
    "driver.managePlan": "Quản Lý Gói",
    "driver.swapHistory": "Lịch Sử Thay Pin",
    "driver.swapHistoryDesc": "Lần thay pin gần đây và giao dịch của bạn",
    "driver.loadMoreHistory": "Tải Lịch Sử Thêm",
    "driver.completed": "hoàn thành",
    "driver.profileInformation": "Thông Tin Hồ Sơ",
    "driver.fullName": "Tên Đầy Đủ",
    "driver.email": "Email",
    "driver.phone": "Số Điện Thoại",
    "driver.saveChanges": "Lưu Thay Đổi",
    "driver.myVehicles": "Xe Của Tôi",
    "driver.myVehiclesDesc": "Quản lý xe đã đăng ký",
    "driver.addVehicle": "Thêm Xe",
    "driver.contactSupport": "Liên Hệ Hỗ Trợ",
    "driver.contactSupportDesc": "Nhận trợ giúp với trải nghiệm EVSwap của bạn",
    "driver.callSupport": "Gọi Hỗ Trợ",
    "driver.liveChat": "Chat Trực Tuyến",
    "driver.reportIssue": "Báo Lỗi",
    "driver.safetyAndSecurity": "An Toàn & Bảo Mật",
    "driver.safetySecurityDesc": "Cài đặt bảo mật tài khoản",
    "driver.changePassword": "Thay Mật Khẩu",
    "driver.twoFactorAuth": "Xác Thực Hai Lần",
    "driver.bookBatterySwap": "Đặt Thay Pin",
    "driver.completeReservation": "Hoàn thành đặt chỗ của bạn trong",
    "driver.moreSteps": "bước tiếp theo",
    "driver.selectVehicle": "Chọn Xe",
    "driver.addNewVehicle": "Thêm Xe Mới",
    "driver.cancel": "Hủy",
    "driver.next": "Tiếp Theo",
    "driver.back": "Quay Lại",
    "driver.chooseTimeSlot": "Chọn Khung Thời Gian",
    "driver.confirmBooking": "Xác Nhận Đặt Chỗ",
    "driver.station": "Trạm:",
    "driver.vehicle": "Xe:",
    "driver.dateTime": "Ngày & Giờ:",
    "driver.total": "Tổng:",
    "driver.bookingConfirmed": "Đặt Chỗ Đã Xác Nhận!",
    "driver.swapReserved": "Đặt chỗ thay pin của bạn hôm nay lúc",
    "driver.bookingCode": "Mã Đặt Chỗ",
    "driver.showQRCode": "Hiển thị mã QR này tại trạm",
    "driver.viewQRCode": "Xem Mã QR",
    "driver.close": "Đóng",
    "driver.checkInQRCode": "Mã QR Check-in",
    "driver.scanAtStation": "Quét mã này tại trạm để bắt đầu thay pin",
    "driver.expiresIn": "Hết hạn trong 2 giờ",
    "driver.saveToPhone": "Lưu vào Điện Thoại",
    "driver.battery": "Pin:",

    // Staff Portal
    "staff.inventory": "Kho Hàng",
    "staff.transactions": "Giao Dịch",
    "staff.reports": "Báo Cáo",
    "staff.incidents": "Sự Cố",
    "staff.queueManagement": "Quản Lý Hàng Chờ",
    "staff.todaysBookings": "Đơn Đặt Hôm Nay",
    "staff.todaysBookingsDesc":
      "Quản lý đặt chỗ khách hàng và khách hàng đến trực tiếp",
    "staff.pending": "đang chờ",
    "staff.inProgress": "đang tiến hành",
    "staff.confirmed": "đã xác nhận",
    "staff.startSwap": "Bắt Đầu Thay Pin",
    "staff.batteryInventory": "Kho Pin",
    "staff.filter": "Lọc",
    "staff.newInspection": "Kiểm Tra Mới",
    "staff.slot": "Slot",
    "staff.health": "Sức Khỏe",
    "staff.voltage": "Điện áp",
    "staff.cycles": "Số vòng",
    "staff.temperature": "Nhiệt độ",
    "staff.lastSwap": "Thay Pin Cuối",
    "staff.full": "đầy",
    "staff.charging": "đang sạc",
    "staff.maintenance": "bảo trì",
    "staff.empty": "trống",
    "staff.recentTransactions": "Giao Dịch Gần Đây",
    "staff.recentTransactionsDesc": "Thay pin hoàn thành hôm nay",
    "staff.subscription": "đăng ký",
    "staff.card": "thẻ",
    "staff.cash": "tiền mặt",
    "staff.out": "ra",
    "staff.in": "vào",
    "staff.shiftSummary": "Tóm Tắt Ca Làm",
    "staff.shiftSummaryDesc": "Hiệu suất của bạn hôm nay",
    "staff.swapsCompleted": "Thay Pin Hoàn Thành",
    "staff.revenueGenerated": "Doanh Thu Được Tạo",
    "staff.avgSwapTime": "Thời Gian Thay Pin Trung Bình",
    "staff.customerRating": "Đánh Giá Khách Hàng",
    "staff.exportReport": "Xuất Báo Cáo",
    "staff.stationAlerts": "Cảnh Báo Trạm",
    "staff.stationAlertsDesc": "Các vấn đề cần chú ý",
    "staff.lowBatteryAlert": "Cảnh Báo Pin Năng Suất",
    "staff.lowBatteryAlertDesc": "3 pin dưới 20% sức khỏe",
    "staff.maintenanceRequired": "Bảo Trì Cần Thiết",
    "staff.maintenanceRequiredDesc": "Slot B1 cần kiểm tra",
    "staff.batterySwapProcess": "Quá Trình Thay Pin",
    "staff.batterySwapProcessDesc":
      "Hoàn thành thay pin cho khách hàng SW-2024-001",
    "staff.customerInformation": "Thông Tin Khách Hàng",
    "staff.name": "Tên",
    "staff.vehicle": "Xe",
    "staff.bookingCode": "Mã Đặt Chỗ",
    "staff.batteryModel": "Mô hình Pin",
    "staff.batteryOut": "Pin OUT",
    "staff.batteryIn": "Pin IN",
    "staff.currentBattery": "Pin Hiện Tại",
    "staff.chargeLevel": "Mức Sạc",
    "staff.destinationSlot": "Slot Đến",
    "staff.newBattery": "Pin Mới",
    "staff.qrCodeScanned": "Mã QR Đã Quét",
    "staff.pinVerified": "PIN Đã Xác Nhận",
    "staff.batterySwapComplete": "Thay Pin Hoàn Thành",
    "staff.markComplete": "Đánh Dấu Hoàn Thành",
    "staff.processPayment": "Xử Lý Thanh Toán",
    "staff.completeAndPrint": "Hoàn Thành & In Hóa Đơn",
    "staff.batteryReturnInspection": "Kiểm Tra Pin Trả Về",
    "staff.batteryReturnInspectionDesc":
      "Kiểm tra pin trả về cho bất kỳ hư hỏng hoặc vấn đề nào",
    "staff.batteryId": "ID Pin",
    "staff.customer": "Khách Hàng",
    "staff.inspectionChecklist": "Danh Sách Kiểm Tra",
    "staff.physicalDamage": "Kiểm tra hư hỏng vật lý",
    "staff.connectorInspection": "Kiểm tra kết nối",
    "staff.temperatureReading": "Đọc nhiệt độ",
    "staff.voltageTest": "Kiểm tra điện áp",
    "staff.capacityVerification": "Xác minh dung lượng",
    "staff.inspectionNotes": "Ghi Chú Kiểm Tra",
    "staff.inspectionNotesPlaceholder": "Bất kỳ vấn đề hoặc quan sát nào...",
    "staff.photoDocumentation": "Tài Liệu Ảnh",
    "staff.takePhoto": "Chụp Ảnh",
    "staff.uploadFile": "Tải Tệp",
    "staff.completeInspection": "Hoàn Thành Kiểm Tra",
    "staff.pointOfSale": "Điểm Bán",
    "staff.pointOfSaleDesc": "Xử lý thanh toán cho thay pin",
    "staff.batterySwapService": "Dịch Vụ Thay Pin",
    "staff.cardPayment": "Thanh Toán Thẻ",
    "staff.qrPayment": "Thanh Toán QR",
    "staff.cashPayment": "Thanh Toán Tiền Mặt",
    "staff.printReceipt": "In Hóa Đơn",
    "staff.todaysSwaps": "Thay Pin Hôm Nay",
    "staff.revenue": "Doanh Thu",
    "staff.avgTime": "Thời Gian Trung Bình",
    "staff.rating": "Đánh Giá",
    "staff.lowBattery": "Pin Năng Suất",

    // Admin Dashboard
    "admin.overview": "Tổng Quan",
    "admin.stations": "Trạm",
    "admin.analytics": "Phân Tích",
    "admin.aiInsights": "Thông Tin AI",
    "admin.users": "Người Dùng",
    "admin.alerts": "Cảnh Báo",
    "admin.settings": "Cài Đặt",
    "admin.totalRevenue": "Tổng Doanh Thu",
    "admin.totalSwaps": "Tổng Lần Thay Pin",
    "admin.activeStations": "Trạm Hoạt Động",
    "admin.customers": "Khách Hàng",
    "admin.allOnline": "Tất Cả Trực Tuyến",
    "admin.newCustomers": "mới",
    "admin.revenueTrends": "Trends Doanh Thu",
    "admin.revenueTrendsDesc": "Doanh thu và số lượng thay pin hàng tháng",
    "admin.batteryHealthDistribution": "Phân Phối Sức Khỏe Pin",
    "admin.batteryHealthDistributionDesc": "Tình trạng hiện tại của bộ pin",
    "admin.avgSwapTime": "Thời Gian Thay Pin Trung Bình",
    "admin.systemUptime": "Thời Gian Hoạt Động Hệ Thống",
    "admin.customerRating": "Đánh Giá Khách Hàng",
    "admin.batteryEfficiency": "Hiệu Suất Pin",
    "admin.stationManagement": "Quản Lý Trạm",
    "admin.filter": "Lọc",
    "admin.addStation": "Thêm Trạm",
    "admin.swaps": "Lần Thay Pin",
    "admin.revenue": "Doanh Thu",
    "admin.utilization": "Sử Dụng",
    "admin.batteryFleetManagement": "Quản Lý Bộ Pin",
    "admin.export": "Xuất",
    "admin.fleetOverview": "Tổng Quan Bộ Pin",
    "admin.totalBatteries": "Tổng Pin",
    "admin.healthy": "Sức Khỏe (>90%)",
    "admin.degraded": "Sức Khỏe (70-90%)",
    "admin.critical": "Sức Khỏe (<70%)",
    "admin.maintenanceSchedule": "Lịch Bảo Trì",
    "admin.urgent": "Khẩn cấp",
    "admin.urgentDesc": "pin",
    "admin.immediateAttention": "Yêu cầu chú ý ngay",
    "admin.thisWeek": "Tuần Này",
    "admin.thisWeekDesc": "pin",
    "admin.scheduledMaintenance": "Bảo Trì Đã Lập",
    "admin.nextMonth": "Tháng Tiếp Theo",
    "admin.nextMonthDesc": "pin",
    "admin.routineInspection": "Kiểm Tra Thường Xuyên",
    "admin.batteryAllocation": "Phân Phối Pin",
    "admin.optimizeAllocation": "Tối Ưu Hóa Phân Phối",
    "admin.customerManagement": "Quản Lý Khách Hàng",
    "admin.searchCustomers": "Tìm khách hàng...",
    "admin.addCustomer": "Thêm Khách Hàng",
    "admin.customer": "Khách Hàng",
    "admin.plan": "Gói",
    "admin.status": "Trạng Thái",
    "admin.actions": "Hành Động",
    "admin.staffManagement": "Quản Lý Nhân Viên",
    "admin.addStaff": "Thêm Nhân Viên",
    "admin.name": "Tên",
    "admin.role": "Vai trò",
    "admin.station": "Trạm",
    "admin.performance": "Hiệu Suất",
    "admin.active": "active",
    "admin.onLeave": "on-leave",
    "admin.suspended": "suspended",
    "admin.aiDemandForecasting": "Dự Báo Yêu Cầu AI",
    "admin.aiDemandForecastingDesc": "Mô hình dự đoán vs thực tế",
    "admin.predicted": "Dự đoán",
    "admin.actual": "Thực tế",
    "admin.confidenceScore": "Độ tin cậy", // Changed from duplicate 'admin.confidence'
    "admin.batteryOptimization": "Tối Ưu Hóa Pin",
    "admin.batteryOptimizationDesc": "Lời khuyên phân phối pin dựa trên AI",
    "admin.recommendation": "Lời khuyên",
    "admin.redistributeBatteries":
      "Chuyển 5 pin từ Nhà Ga Sân Bay đến Trung Tâm Thành Phố",
    "admin.schedulePreemptive":
      "Lập lịch bảo trì khẩn cấp cho 12 pin đang bị giảm sức khỏe",
    "admin.impact": "Tác động",
    "admin.increaseUtilization": "+15% cải thiện sử dụng",
    "admin.reduceMaintenance": "Giảm 30% bảo trì khẩn cấp",
    "admin.confidence": "Độ tin cậy", // This is the main confidence key
    "admin.systemAlerts": "Cảnh Báo Hệ Thống",
    "admin.criticalLevel": "cảnh báo", // Changed from duplicate 'admin.critical'
    "admin.warning": "cảnh báo",
    "admin.info": "thông tin",
    "admin.stationBatteryHealth": "Sức Khỏe Pin Trạm B1 dưới 50%",
    "admin.highDemandPredicted": "Yêu cầu cao dự đoán từ 6-8 PM",
    "admin.monthlyTarget": "Đạt mục tiêu doanh thu hàng tháng",
    "admin.paymentGateway": "Lỗi thời gian chờ cổng thanh toán",
    "admin.allStations": "Tất Cả Trạm",
    "admin.system": "Hệ Thống",
    "admin.markResolved": "Đánh Dấu Đã Giải Quyết",
    "admin.viewDetails": "Xem Chi Tiết",
    "admin.batteries": "Pin",
    "admin.staff": "Nhân Viên",

    // Admin Battery Management
    "admin.sevenDays": "7 ngày",
    "admin.thirtyDays": "30 ngày",
    "admin.ninetyDays": "90 ngày",
    "admin.urgentBatteries": "Khẩn cấp: 8 pin",
    "admin.thisWeekBatteries": "Tuần này: 15 pin",
    "admin.nextMonthBatteries": "Tháng sau: 23 pin",
    "admin.downtownHub": "Trung Tâm Thành Phố",
    "admin.mallStation": "Trạm Trung Tâm Thương Mại",
    "admin.airportTerminal": "Nhà Ga Sân Bay",
    "admin.highwayRestStop": "Trạm Nghỉ Cao Tốc",
    "admin.universityCampus": "Khuôn Viên Đại Học",

    // Admin Customer & Staff Plans/Roles
    "admin.monthlyUnlimited": "Không Giới Hạn Hàng Tháng",
    "admin.payPerSwap": "Trả Theo Lần Thay",
    "admin.enterprise": "Doanh Nghiệp",
    "admin.stationManager": "Quản Lý Trạm",
    "admin.technician": "Kỹ Thuật Viên",
    "admin.supervisor": "Giám Sát Viên",

    // Admin Alerts Messages
    "admin.alertTime2Min": "2 phút trước",
    "admin.alertTime15Min": "15 phút trước",
    "admin.alertTime1Hour": "1 giờ trước",
    "admin.alertTime2Hours": "2 giờ trước",

    // Common
    "common.logout": "Đăng Xuất",
    "common.loading": "Đang Tải...",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.edit": "Sửa",
    "common.delete": "Xóa",
    "common.view": "Xem",
    "common.close": "Đóng",
    "common.settings": "Cài Đặt",
  },
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("vi");

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)["en"]] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
